services:
  client:
    container_name: reviews_app_client
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    depends_on:
      - api
    ports:
      - 7000:7000
    networks:
      - reviews-net
  db:
    container_name: reviews_app_db
    image: postgres
    ports:
      - 0.0.0.0:5432:5432
    env_file:
      - ./server/.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - reviews-net

  cache:
    container_name: reviews_app_cache
    image: redis:8.0-M03-alpine3.21
    ports:
      - 0.0.0.0:6379:6379
    networks:
      - reviews-net

  api:
    container_name: reviews_app_api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    restart: always
    volumes:
      - ./storage:/storage
    networks:
      - reviews-net
    depends_on:
      - db
      - cache
    env_file:
      - ./server/.env

networks:
  reviews-net:
